version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - feature/AppVeyor-ci
image: Previous Visual Studio 2017
install:
- ps: >-
    npm install

    cd client

    npm install

    cd ..
build_script:
- ps: >-
    # Build MCS-Lite console (Webpack)

    cd client

    npm run build:global

    cd ..


    # Build App (NW.js)

    npm run build:windows


    # Compression

    cd ./out_win/mcs-lite-app

    find . -type d -name "win*" -maxdepth 1 -mindepth 1 -exec zip -rq {}.zip {}  \;

    ls .

    cd ../..
deploy:
- provider: GitHub
  auth_token:
    secure: 19srBF6KWNDItlgzhQGIeKrPn40xjgnhxEaGjM9h9RO+sfASEdNaPk5KDyQJlQ9S
  artifact: ./out/mcs-lite-app/*.{zip}
  prerelease: true